# File: .github/workflows/python-tests.yml

name: Test and Build Docker Images

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  # --- Задача 1: Запуск тестов ---
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r backend/requirements.txt

      - name: Run tests with pytest
        env: # Устанавливаем PYTHONPATH для этого шага
          PYTHONPATH: ${{ github.workspace }}
        run: |
          # Запускаем pytest
          pytest backend/tests/

  # --- Задача 2: Сборка Docker образов ---
  build_images:
    runs-on: ubuntu-latest
    needs: test # Запускать только после успешных тестов

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: linux/amd64

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build backend image
        run: |
          docker build \
            --tag myapp-backend:latest \
            --file backend/Dockerfile \
            ./backend

      - name: Build frontend image
        run: |
          docker build \
            --tag myapp-frontend:latest \
            --file frontend/Dockerfile \
            ./frontend

      - name: Verify images built
        run: |
          echo "Listing built Docker images:"
          docker images myapp-backend:latest
          docker images myapp-frontend:latest
